# Use Node.js base image
FROM node:16-slim

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY frontend/package.json /app/
COPY frontend/package-lock.json /app/
RUN npm install

# Copy all frontend files into the container
COPY ./frontend /app

# Expose frontend port
EXPOSE 3000

# Run the Next.js development server
CMD ["npm", "run", "dev"]
